Repository ohsoou/LibrarySystem, pull requests merged in 2021-08, with the labels that each got.

#4 enhancement: overdue, overdue_count DAO/DTO
  Library_System/src/model/Overdue_count_dao.java
  Library_System/src/model/Overdue_count_dto.java
  Library_System/src/model/Overdue_dao.java
  Library_System/src/model/Overdue_dto.java
Labels: enhancement

#5 enhancement/student DAO/DTO
  .gitignore
  Library_System/src/db/DBConnector.java
  Library_System/src/model/StudentDao.java
  Library_System/src/model/StudentDto.java
Labels: enhancement

#8 update: delete duplicated file named snake case
  Library_System/src/model/Overdue_count_dao.java
  Library_System/src/model/Overdue_count_dto.java
  Library_System/src/model/Overdue_dao.java
  Library_System/src/model/Overdue_dto.java
Labels: update

#10 Update/#9 db connector import overdue,overdue count
  Library_System/src/model/OverdueCountDao.java
  Library_System/src/model/OverdueDao.java
Labels: update

#12 update: delete useless import/update sql/update method
  Library_System/src/model/OverdueCountDao.java
  Library_System/src/model/OverdueCountDto.java
  Library_System/src/model/OverdueDao.java
  Library_System/src/model/OverdueDto.java
Labels: update

#14 update: import_update, sql_update
  Library_System/src/model/OverdueCountDao.java
  Library_System/src/model/OverdueCountDto.java
  Library_System/src/model/OverdueDao.java
  Library_System/src/model/OverdueDto.java
Labels: update

#16 Enhancement/15 update overdue model
  Library_System/src/model/OverdueCountDao.java
  Library_System/src/model/OverdueDao.java
  Library_System/src/model/OverdueDto.java
Labels: enhancement

#19 delete annotation needless
  Library_System/src/db/DBConnector.java
Labels: update

#21 Update/20 confirm git
  Library_System/src/model/OverdueDao.java
Labels: update

#23 Enhancement/22 db book dao/dto
  Library_System/src/model/BookDao.java
  Library_System/src/model/BookDto.java
Labels: enhancement

#24 Enhancement/17 loan dao,loan dto
  Library_System/src/model/LoanDao.java
  Library_System/src/model/LoanDto.java
Labels: enhancement

#27 Commit Bookinfo DAO/DTO & bookclassification DAO/DTO
  Library_System/src/model/BookClassificationDao.java
  Library_System/src/model/BookClassificationDto.java
  Library_System/src/model/BookinfoDao.java
  Library_System/src/model/BookinfoDto.java
Labels: enhancement

#35 bookinfo update문 수정
  Library_System/src/model/BookinfoDao.java
Labels: update

#37 change to file edited by ParkCheonhyuk
  Library_System/src/model/BookClassificationDao.java
Labels: update

#40 Update/30 loan dao2
  Library_System/src/model/LoanDao.java
Labels: update

#45 upload searchPanel-Basic in managerPage
  Library_System/src/view/component/DefaultBookCategoryDropDown.java
  Library_System/src/view/component/DefaultBookSearchBar.java
  Library_System/src/view/manager/searchPanel.java
Labels: enhancement

#51 Enhancement/41 arrange manager page
  Library_System/src/view/DefaultFrame.java
  Library_System/src/view/component/DefaultBtn.java
  Library_System/src/view/manager.java
  Library_System/src/view/manager/ManagerPanel.java
  Library_System/src/view/manager/SearchPanel.java
  Library_System/src/view/manager/TitleLabel.java
  Library_System/src/view/manager/TitlePanel.java
Labels: enhancement

#50 테스트용 로그인페이지입니다
  Library_System/src/image/login.png
  Library_System/src/image/pw_img.png
  Library_System/src/image/user_img.png
  Library_System/src/view/login/idLabel.java
  Library_System/src/view/login/idTextField.java
  Library_System/src/view/login/loginButton.java
  Library_System/src/view/login/loginPanel.java
  Library_System/src/view/login/loginTitleLable.java
  Library_System/src/view/login/pwLabel.java
  Library_System/src/view/login/pwTextField.java
Labels: enhancement

#54 Enhancement/52 create default panel
  Library_System/src/view/component/DefaultPanel.java
  Library_System/src/view/login/loginPanel.java
  Library_System/src/view/manager/ManagerPanel.java
  Library_System/src/view/manager/SearchPanel.java
  Library_System/src/view/manager/TitlePanel.java
Labels: enhancement

#56 create allbookinfo dao/dto
  Library_System/src/model/dao/AllBookInfoDao.java
  Library_System/src/model/dto/AllBookInfo.java
Labels: enhancement

#58 Enhancement/57 update default button
  Library_System/src/view/component/DefaultBtn.java
  Library_System/src/view/component/DefaultButton.java
  Library_System/src/view/manager/SearchPanel.java
  Library_System/src/view/manager/TitlePanel.java
Labels: enhancement

#62 Enhancement/61 create manager dialog
  Library_System/image/NoBookImage.PNG
  Library_System/src/view/component/RoundTextField.java
  Library_System/src/view/manager/BookImageFileChooser.java
  Library_System/src/view/manager/FilePanel.java
  Library_System/src/view/manager/FormPanel.java
  Library_System/src/view/manager/ManagerDialog.java
  Library_System/src/view/manager/OpenDialogListener.java
  Library_System/src/view/manager/TitlePanel.java
Labels: enhancement

#68 Enhancemet/63 design cancel submit button in dialog
  Library_System/src/view/manager/FilePanel.java
  Library_System/src/view/manager/ManagerDialog.java
Labels: enhancement

#69 update set defaultImage if not selected file
  Library_System/src/view/manager/FilePanel.java
Labels: update

#72 add ActionListener on cancel Button
  Library_System/src/view/manager/ManagerDialog.java
Labels: enhancement

#73 update /65/student DTO
  Library_System/src/model/dto/Student.java
Labels: update

#81 Enhancement/77/new book&suggestion book
  Library_System/src/image/login.png
  Library_System/src/image/pw_img.png
  Library_System/src/image/user_img.png
  Library_System/src/model/dao/AllBookInfoDao.java
  Library_System/src/model/dao/BookDao.java
  Library_System/src/model/dao/BookinfoDao.java
  Library_System/src/model/dto/AllBookInfo.java
  Library_System/src/model/dto/Book.java
  Library_System/src/model/dto/Bookinfo.java
  Library_System/src/view/DefaultFrame.java
  Library_System/src/view/advertising/AdActionButton.java
  Library_System/src/view/advertising/AdCenterPanel.java
  Library_System/src/view/advertising/AdImageButton.java
  Library_System/src/view/advertising/AdTopPanel.java
  Library_System/src/view/advertising/AdvertisingPanel.java
  Library_System/src/view/advertising/NewBookPanel.java
  Library_System/src/view/advertising/SuggestionBookPanel.java
  Library_System/src/view/component/DefaultButton.java
  bookimage/(시나공 2021) 컴퓨터활용능력1급 필기.jpg
  bookimage/COSMOS.jpg
  bookimage/강경원의 백 투 베이직.jpg
  bookimage/강아지 심리 백과.jpg
  bookimage/까눌레.jpg
  bookimage/깨어난 포스.jpg
  bookimage/꽃을 사는 여자들.jpg
  bookimage/나는 걷는다 고로 존재한다.jpg
  bookimage/나의 라임 오렌지나무.jpg
  bookimage/달러구트 꿈 백화점.jpg
  bookimage/무림오적.1.jpg
  bookimage/무림오적.2.jpg
  bookimage/무림오적.3.jpg
  bookimage/미드나잇 라이브러리.jpg
  bookimage/밝은 밤.jpg
  bookimage/방구석 미술관.jpg
  bookimage/봄이다.jpg
  bookimage/사람이 있었네.jpg
  bookimage/사장의 철학.jpg
  bookimage/성공회 신학.jpg
  bookimage/식객 허영만의 백반기행 세트.jpg
  bookimage/신의 화살.jpg
  bookimage/아낌 없이 주는 나무.jpg
  bookimage/약속의 땅.jpg
  bookimage/완전한 행복.jpg
  bookimage/우리가 농구에 미치는 이유.jpg
  bookimage/인간 실격.jpg
  bookimage/자기 앞의 생.jpg
  bookimage/제로부터 시작하는 이세계 생활 3장.jpg
  bookimage/최악을 극복 하는 힘.jpg
Labels: enhancement, update

#82 update PR/변수명 수정 완료
  Library_System/src/model/dao/BookDao.java
  Library_System/src/view/DefaultFrame.java
  Library_System/src/view/advertising/AdActionButton.java
  Library_System/src/view/advertising/AdCenterPanel.java
  Library_System/src/view/advertising/AdImageButton.java
  Library_System/src/view/advertising/AdTopPanel.java
  Library_System/src/view/advertising/NewBookPanel.java
  Library_System/src/view/advertising/SuggestionBookPanel.java
  image/(시나공 2021) 컴퓨터활용능력1급 필기.jpg
  image/COSMOS.jpg
  image/강경원의 백 투 베이직.jpg
  image/강아지 심리 백과.jpg
  image/까눌레.jpg
  image/깨어난 포스.jpg
  image/꽃을 사는 여자들.jpg
  image/나는 걷는다 고로 존재한다.jpg
  image/나의 라임 오렌지나무.jpg
  image/달러구트 꿈 백화점.jpg
  image/무림오적.1.jpg
  image/무림오적.2.jpg
  image/무림오적.3.jpg
  image/미드나잇 라이브러리.jpg
  image/밝은 밤.jpg
  image/방구석 미술관.jpg
  image/봄이다.jpg
  image/사람이 있었네.jpg
  image/사장의 철학.jpg
  image/성공회 신학.jpg
  image/식객 허영만의 백반기행 세트.jpg
  image/신의 화살.jpg
  image/아낌 없이 주는 나무.jpg
  image/약속의 땅.jpg
  image/완전한 행복.jpg
  image/우리가 농구에 미치는 이유.jpg
  image/인간 실격.jpg
  image/자기 앞의 생.jpg
  image/제로부터 시작하는 이세계 생활 3장.jpg
  image/최악을 극복 하는 힘.jpg
Labels: update

#84 Enhancement/#83 table panel&list paging button&list table
  Library_System/src/view/BookListPagingButton.java
  Library_System/src/view/BookListTable.java
  Library_System/src/view/TablePanel.java
Labels: enhancement

#85 Enhancement/75 update manger table
  Library_System/src/view/BookListPagingButton.java
  Library_System/src/view/BookListTable.java
  Library_System/src/view/DefaultFrame.java
  Library_System/src/view/TablePanel.java
  Library_System/src/view/component/DefaultButton.java
  Library_System/src/view/manager/BookListTable.java
  Library_System/src/view/manager/ManagerPanel.java
  Library_System/src/view/manager/TablePanel.java
  Library_System/src/view/manager/TitlePanel.java
  Library_System/src/view/manager/dialog/BookImageFileChooser.java
  Library_System/src/view/manager/dialog/FilePanel.java
  Library_System/src/view/manager/dialog/FormPanel.java
  Library_System/src/view/manager/dialog/ManagerDialog.java
  Library_System/src/view/manager/dialog/OpenDialogListener.java
  Library_System/src/view/manager_Table.java
Labels: enhancement

#87 doc: change image forder
  Library_System/image/(시나공 2021) 컴퓨터활용능력1급 필기.jpg
  Library_System/image/COSMOS.jpg
  Library_System/image/main_btn_01.png
  Library_System/image/main_btn_02.png
  Library_System/image/main_btn_03.png
  Library_System/image/main_btn_04.png
  Library_System/image/강경원의 백 투 베이직.jpg
  Library_System/image/강아지 심리 백과.jpg
  Library_System/image/까눌레.jpg
  Library_System/image/깨어난 포스.jpg
  Library_System/image/꽃을 사는 여자들.jpg
  Library_System/image/나는 걷는다 고로 존재한다.jpg
  Library_System/image/나의 라임 오렌지나무.jpg
  Library_System/image/달러구트 꿈 백화점.jpg
  Library_System/image/무림오적.1.jpg
  Library_System/image/무림오적.2.jpg
  Library_System/image/무림오적.3.jpg
  Library_System/image/미드나잇 라이브러리.jpg
  Library_System/image/밝은 밤.jpg
  Library_System/image/방구석 미술관.jpg
  Library_System/image/봄이다.jpg
  Library_System/image/사람이 있었네.jpg
  Library_System/image/사장의 철학.jpg
  Library_System/image/성공회 신학.jpg
  Library_System/image/식객 허영만의 백반기행 세트.jpg
  Library_System/image/신의 화살.jpg
  Library_System/image/아낌 없이 주는 나무.jpg
  Library_System/image/약속의 땅.jpg
  Library_System/image/완전한 행복.jpg
  Library_System/image/우리가 농구에 미치는 이유.jpg
  Library_System/image/인간 실격.jpg
  Library_System/image/자기 앞의 생.jpg
  Library_System/image/제로부터 시작하는 이세계 생활 3장.jpg
  Library_System/image/최악을 극복 하는 힘.jpg
Labels: documentation

#89 Enhancement/88 create summary text field in manager
  Library_System/src/view/component/DefaultPanel.java
  Library_System/src/view/manager/BookListPagingButton.java
  Library_System/src/view/manager/TablePanel.java
  Library_System/src/view/manager/TitlePanel.java
  Library_System/src/view/manager/dialog/BookImageFileChooser.java
  Library_System/src/view/manager/dialog/ButtonPanel.java
  Library_System/src/view/manager/dialog/FilePanel.java
  Library_System/src/view/manager/dialog/FormPanel.java
  Library_System/src/view/manager/dialog/ManagerDialog.java
  Library_System/src/view/manager_UnderBtn.java
Labels: enhancement, update

#91 update: resize table row
  Library_System/src/view/manager/BookListTable.java
  Library_System/src/view/manager/TablePanel.java
Labels: update

#96 Enhancement/#93-return_page
  Library_System/src/view/return/returnBtn.java
  Library_System/src/view/return/returnPanel.java
  Library_System/src/view/return/returnTable.java
  Library_System/src/view/return/returnTitleLable.java
Labels: enhancement

#102 solve conflict
  Library_System/src/view/DefaultFrame.java
Labels: update

#103 when no exist image, set NoBookImage.png
  Library_System/src/view/manager/dialog/ManagerDialog.java
Labels: update

#106 update/105/StudentDao 수정
  Library_System/src/model/dao/StudentDao.java
Labels: update

#110 Enhancement/104 set search option connect db
  Library_System/src/model/dao/AllBookInfoDao.java
  Library_System/src/view/manager/BookListTable.java
  Library_System/src/view/manager/ManagerPanel.java
  Library_System/src/view/manager/SearchPanel.java
  Library_System/src/view/manager/TablePanel.java
  Library_System/src/view/manager/TitlePanel.java
  Library_System/src/view/manager/dialog/FormPanel.java
Labels: enhancement

#112 update: refactor table panel
  Library_System/.metadata/.gitignore
  Library_System/.metadata/.plugins/org.eclipse.core.resources/.root/.gitignore
  Library_System/.metadata/.plugins/org.eclipse.core.resources/.root/.indexes/.gitignore
  Library_System/.metadata/.plugins/org.eclipse.core.resources/.safetable/.gitignore
  Library_System/.metadata/.plugins/org.eclipse.e4.workbench/.gitignore
  Library_System/.metadata/.plugins/org.eclipse.jdt.core/.gitignore
  Library_System/.metadata/.plugins/org.eclipse.jdt.ui/.gitignore
  Library_System/.metadata/.plugins/org.eclipse.m2e.logback.configuration/.gitignore
  Library_System/.metadata/.plugins/org.eclipse.oomph.setup/.gitignore
  Library_System/.metadata/.plugins/org.eclipse.rse.core/initializerMarks/.gitignore
  Library_System/.metadata/.plugins/org.eclipse.tips.ide/.gitignore
  Library_System/.metadata/.plugins/org.eclipse.tm.terminal.view.ui/.executables/.gitignore
  Library_System/.metadata/.plugins/org.eclipse.ui.intro/.gitignore
  Library_System/.metadata/.plugins/org.eclipse.ui.workbench/.gitignore
  Library_System/src/view/component/DefaultSearchedTablePanel.java
  Library_System/src/view/manager/ManagerPanel.java
Labels: update

#117 Enhancement/113/login page v1
  Library_System/image/password_img.png
  Library_System/image/user_img.png
  Library_System/src/view/login/IdLabel.java
  Library_System/src/view/login/IdTextField.java
  Library_System/src/view/login/ImageResize.java
  Library_System/src/view/login/LoginButton.java
  Library_System/src/view/login/LoginErrorLabel.java
  Library_System/src/view/login/LoginPanel.java
  Library_System/src/view/login/LoginTitleLable.java
  Library_System/src/view/login/PwLabel.java
  Library_System/src/view/login/PwTextField.java
  Library_System/src/view/login/idLabel.java
  Library_System/src/view/login/loginButton.java
  Library_System/src/view/login/loginPanel.java
  Library_System/src/view/login/pwLabel.java
Labels: enhancement

#118 Enhancement/90 add function table
  Library_System/src/view/component/DefaultSearchedTablePanel.java
  Library_System/src/view/manager/BookListTable.java
Labels: enhancement

#120 Enhancement/119 set book info when update click
  Library_System/src/view/component/DefaultTablePanel.java
  Library_System/src/view/manager/ManagerPanel.java
  Library_System/src/view/manager/SearchPanel.java
  Library_System/src/view/manager/TitlePanel.java
  Library_System/src/view/manager/dialog/FilePanel.java
  Library_System/src/view/manager/dialog/FormPanel.java
  Library_System/src/view/manager/dialog/ManagerDialog.java
  Library_System/src/view/manager/dialog/OpenDialogListener.java
Labels: enhancement, update

#122 Enhancement/121 submit update table
  Library_System/src/model/dao/BookinfoDao.java
  Library_System/src/view/DefaultFrame.java
  Library_System/src/view/component/DefaultTablePanel.java
  Library_System/src/view/manager/BookListWithSelectedBook.java
  Library_System/src/view/manager/ManagerPanel.java
  Library_System/src/view/manager/TitlePanel.java
  Library_System/src/view/manager/dialog/ButtonPanel.java
  Library_System/src/view/manager/dialog/FilePanel.java
  Library_System/src/view/manager/dialog/FormPanel.java
  Library_System/src/view/manager/dialog/ManagerDialog.java
Labels: enhancement, update

#126 Enhancement/123 change panel to frame
  Library_System/src/view/DefaultFrame.java
  Library_System/src/view/manager/ManagerFrame.java
  Library_System/src/view/manager/TitlePanel.java
  Library_System/src/view/manager/dialog/ButtonPanel.java
Labels: enhancement, update

#125 update: loan_DAO/DTO update
  Library_System/src/model/dao/LoanDao.java
  Library_System/src/model/dto/Loan.java
Labels: update

#131 DeleteRecord & ExitRecord 추가
  Library_System/src/view/manager/TitlePanel.java
Labels: enhancement

#135 Enhancement/129 next page
  Library_System/image/componentImg/main_btn_01.png
  Library_System/image/componentImg/main_btn_02.png
  Library_System/image/componentImg/main_btn_03.png
  Library_System/image/componentImg/main_btn_04.png
  Library_System/image/componentImg/password_img.png
  Library_System/image/componentImg/user_img.png
  Library_System/src/view/advertising/AdActionButton.java
  Library_System/src/view/advertising/AdCenterPanel.java
  Library_System/src/view/advertising/AdImageButton.java
  Library_System/src/view/advertising/AdTopPanel.java
  Library_System/src/view/advertising/AdvertisingFrame.java
  Library_System/src/view/advertising/AdvertisingPanel.java
  Library_System/src/view/advertising/NewBookPanel.java
  Library_System/src/view/advertising/SuggestionBookPanel.java
  Library_System/src/view/advertising/details/AdDetailsLabel.java
  Library_System/src/view/advertising/details/AdDetailsView.java
  Library_System/src/view/advertising/details/AdDetailsViewButton.java
  Library_System/src/view/login/IdLabel.java
  Library_System/src/view/login/LoginFrame.java
  Library_System/src/view/login/LoginPanel.java
  Library_System/src/view/login/PwLabel.java
Labels: enhancement, update

#133 update: listByStudentNum, updateReturnDate 수정
  Library_System/src/model/dao/LoanDao.java
Labels: update

#137 DeleteRecord & ExitRecord 수정
  Library_System/src/view/manager/TitlePanel.java
Labels: update

#139 Enhancement/129 next page
  Library_System/src/view/advertising/AdImageButton.java
  Library_System/src/view/advertising/AdvertisingFrame.java
  Library_System/src/view/component/DefaultFrame.java
  Library_System/src/view/login/LoginFrame.java
  Library_System/src/view/main/CenterPanel.java
  Library_System/src/view/main/MainButton.java
  Library_System/src/view/main/MainFrame.java
  Library_System/src/view/main/MainNextAction.java
  Library_System/src/view/main/MainPanel.java
  Library_System/src/view/main/TopPanel.java
  Library_System/src/view/manager/ManagerFrame.java
  Library_System/src/view/manager/TitlePanel.java
Labels: enhancement, update

#138 Enhancement/#134 return package name,return table update
  Library_System/src/view/returns/ReturnBtn.java
  Library_System/src/view/returns/ReturnPanel.java
  Library_System/src/view/returns/ReturnTable.java
  Library_System/src/view/returns/ReturnTitleLable.java
  Library_System/src/view/returns/SelectTable.java
Labels: enhancement

#144 Update/143 refactoring
  Library_System/image/NoBookImage.PNG
  Library_System/image/달러구트꿈백화점.png
  Library_System/src/view/advertising/AdActionButton.java
  Library_System/src/view/advertising/AdCenterPanel.java
  Library_System/src/view/advertising/AdImageButton.java
  Library_System/src/view/advertising/AdTopPanel.java
  Library_System/src/view/advertising/AdvertisingFrame.java
  Library_System/src/view/advertising/NewBookPanel.java
  Library_System/src/view/advertising/SuggestionBookPanel.java
  Library_System/src/view/defaultcomponent/BookListPagingButton.java
  Library_System/src/view/defaultcomponent/BookListTable.java
  Library_System/src/view/defaultcomponent/BookListWithSelectedBook.java
  Library_System/src/view/defaultcomponent/DefaultBookCategoryDropDown.java
  Library_System/src/view/defaultcomponent/DefaultBookSearchBar.java
  Library_System/src/view/defaultcomponent/DefaultButton.java
  Library_System/src/view/defaultcomponent/DefaultFrame.java
  Library_System/src/view/defaultcomponent/DefaultPanel.java
  Library_System/src/view/defaultcomponent/DefaultTablePanel.java
  Library_System/src/view/defaultcomponent/IFrame.java
  Library_System/src/view/defaultcomponent/NextPrevTablePagingButton.java
  Library_System/src/view/defaultcomponent/RoundTextField.java
  Library_System/src/view/login/LoginButton.java
  Library_System/src/view/login/LoginFrame.java
  Library_System/src/view/main/MainFrame.java
  Library_System/src/view/main/TopPanel.java
  Library_System/src/view/manager/ManagerFrame.java
  Library_System/src/view/manager/SearchPanel.java
  Library_System/src/view/manager/TitlePanel.java
  Library_System/src/view/manager/dialog/ButtonPanel.java
  Library_System/src/view/manager/dialog/FilePanel.java
  Library_System/src/view/manager/dialog/FormPanel.java
  Library_System/src/view/manager/dialog/ManagerDialog.java
  Library_System/src/view/returns/ReturnBtn.java
  Library_System/src/view/returns/ReturnPanel.java
Labels: enhancement, update

#148 Update_MainPage_MainNextAction/ Btn_connect_Action
  Library_System/src/view/main/MainNextAction.java
Labels: update

#152 Enhancement/109 loan selection
  Library_System/src/db/DBConnector.java
  Library_System/src/view/rental/SearchedTableTopPanel.java
  Library_System/src/view/rental/SearchedTableUnderPanel.java
  Library_System/src/view/rental/TestFrame.java
  Library_System/src/view/rental/UserSelection.java
Labels: enhancement, update

#149 update: ReturnFrame으로 변경, ReturnTitleLable 레이아웃 수정
  Library_System/src/view/returns/ReturnFrame.java
  Library_System/src/view/returns/ReturnTitleLable.java
Labels: update

#151 mian title 추가
  Library_System/src/view/main/MainTitleLabel.java
  Library_System/src/view/main/MainTitlePanel.java
Labels: update

#156 LoginHost Class 생성
  Library_System/src/view/login/LoginFrame.java
  Library_System/src/view/login/LoginHost.java
Labels: update

#158 update: table align 수정
  Library_System/src/view/returns/ReturnTable.java
Labels: update

#159 Login frame/Host/DAO issue#155
  Library_System/src/model/dao/StudentDao.java
  Library_System/src/view/login/LoginFrame.java
  Library_System/src/view/login/LoginHost.java
Labels: update

#160 Enhancement/129 next page
  Library_System/image/componentImg/prev_arrow_btn.png
  Library_System/src/db/DBConnector.java
  Library_System/src/view/advertising/AdvertisingFrame.java
  Library_System/src/view/defaultcomponent/DefaultFrame.java
  Library_System/src/view/login/LoginFrame.java
  Library_System/src/view/main/MainNextAction.java
  Library_System/src/view/main/MainTitleLabel.java
  Library_System/src/view/main/MainTitlePanel.java
  Library_System/src/view/main/TopPanel.java
  Library_System/src/view/returns/ReturnFrame.java
Labels: enhancement, update

#162 Update/70 fix error
  Library_System/image/달러구트 꿈 백화점.jpg
  Library_System/src/db/DBConnector.java
  Library_System/src/model/dao/BookinfoDao.java
  Library_System/src/view/advertising/AdImageButton.java
  Library_System/src/view/advertising/details/AdDetailsViewButton.java
  Library_System/src/view/defaultcomponent/DefaultButton.java
  Library_System/src/view/login/LoginButton.java
  Library_System/src/view/login/LoginFrame.java
  Library_System/src/view/main/MainButton.java
  Library_System/src/view/manager/BookListWithSelectedBook.java
  Library_System/src/view/manager/ManagerFrame.java
  Library_System/src/view/manager/TitlePanel.java
  Library_System/src/view/manager/dialog/ButtonPanel.java
  Library_System/src/view/manager/dialog/ManagerDialog.java
Labels: enhancement, update

#169 LoginFrame 수정
  Library_System/src/view/login/LoginFrame.java
Labels: update

#170 Update/fix error
  Library_System/src/model/dao/BookinfoDao.java
  Library_System/src/view/advertising/AdImageButton.java
  Library_System/src/view/advertising/details/AdDetailsViewButton.java
  Library_System/src/view/defaultcomponent/DefaultButton.java
  Library_System/src/view/login/LoginFrame.java
  Library_System/src/view/main/MainButton.java
  Library_System/src/view/main/TopPanel.java
  Library_System/src/view/manager/BookListWithSelectedBook.java
  Library_System/src/view/manager/ManagerFrame.java
  Library_System/src/view/manager/TitlePanel.java
  Library_System/src/view/manager/dialog/ButtonPanel.java
  Library_System/src/view/manager/dialog/ManagerDialog.java
Labels: duplicate, update

#172 Update/login
  Library_System/src/model/dao/StudentDao.java
  Library_System/src/model/dto/Student.java
  Library_System/src/view/login/LoginFrame.java
Labels: duplicate, update

#173 error: no show duplicate book in ad
  Library_System/src/view/advertising/NewBookPanel.java
  Library_System/src/view/advertising/SuggestionBookPanel.java
Labels: bug, duplicate, update

#174 Update/fix error
  Library_System/src/model/dao/StudentDao.java
  Library_System/src/view/login/LoginFrame.java
  Library_System/src/view/login/LoginHost.java
Labels: duplicate, update

#175 error: login logic
  Library_System/src/view/login/LoginFrame.java
Labels: duplicate, update

#178 Rental end page/164
  Library_System/image/componentImg/rentalEnd_btn.png
  Library_System/src/view/login/LoginFrame.java
  Library_System/src/view/rental/rentalEndPage/EndPageTimeLabel.java
  Library_System/src/view/rental/rentalEndPage/rentalEndHomeBtn.java
  Library_System/src/view/rental/selectBtnAction.java
Labels: duplicate, enhancement

#180 AdTitleLabel 추가
  Library_System/src/view/advertising/AdTitleLabel.java
  Library_System/src/view/advertising/AdTitlePanel.java
  Library_System/src/view/advertising/AdTopPanel.java
Labels: enhancement

#181 Enhancement.164 rental end page
  Library_System/src/model/dao/LoanDao.java
  Library_System/src/view/rental/selectBtnAction.java
Labels: bug, duplicate, enhancement

#187 위치조정 완료
  Library_System/src/view/advertising/AdTitleLabel.java
Labels: update

#186 update/ return 이전버튼 추가
  Library_System/src/view/returns/PrevBtnLabel.java
  Library_System/src/view/returns/ReturnFrame.java
Labels: update

#189 rentalEndPage/164/오류사항 수정완료
  Library_System/src/view/advertising/AdCenterPanel.java
  Library_System/src/view/advertising/AdTitleLabel.java
  Library_System/src/view/advertising/AdvertisingFrame.java
  Library_System/src/view/advertising/NewBookPanel.java
  Library_System/src/view/advertising/SuggestionBookPanel.java
  Library_System/src/view/advertising/details/AdDetailsViewButton.java
  Library_System/src/view/rental/rentalEndPage/EndPageTimeLabel.java
  Library_System/src/view/rental/rentalEndPage/EndpageLabel.java
  Library_System/src/view/rental/rentalEndPage/rentalEndFrame.java
  Library_System/src/view/rental/rentalEndPage/rentalEndHomeBtn.java
Labels: update

#190 update: extend,return page layout수정, Table 정렬 for문으로 수정
  Library_System/src/view/extend/ExtendFrame.java
  Library_System/src/view/extend/ExtendPanel.java
  Library_System/src/view/extend/ExtendTable.java
  Library_System/src/view/returns/PrevBtnLabel.java
  Library_System/src/view/returns/ReturnFrame.java
  Library_System/src/view/returns/ReturnPanel.java
  Library_System/src/view/returns/ReturnTable.java
Labels: update

#193 Update/#192 extend panel title update
  Library_System/src/view/extend/ExtendPanel.java
Labels: update

#196 맑은 고딕 으로 수정
  Library_System/src/view/advertising/AdTitleLabel.java
Labels: update

#198 return&extendTable hotfix
  Library_System/src/view/extend/ExtendTable.java
  Library_System/src/view/returns/ReturnTable.java
Labels: update

#201 change adTitle depend on button
  Library_System/src/view/advertising/AdActionButton.java
  Library_System/src/view/advertising/AdTitleLabel.java
  Library_System/src/view/advertising/AdTitlePanel.java
  Library_System/src/view/advertising/AdTopPanel.java
Labels: duplicate, enhancement, update

#204 return/extend Table 수정
  Library_System/src/view/extend/ExtendTable.java
  Library_System/src/view/returns/ReturnTable.java
Labels: update

#205 Main action
  Library_System/src/view/main/MainNextAction.java
  Library_System/src/view/main/MainTitleLabel.java
  Library_System/src/view/manager/TitleLabel.java
Labels: update

#207 update:extend/return layout 수정
  Library_System/src/view/extend/ExtendFrame.java
  Library_System/src/view/extend/ExtendPanel.java
  Library_System/src/view/returns/ReturnFrame.java
  Library_System/src/view/returns/ReturnPanel.java
Labels: update

#209 change cursor hover table
  Library_System/src/view/defaultcomponent/BookListTable.java
Labels: update

#211 update focusing color
  Library_System/src/view/returns/ReturnTable.java
  Library_System/src/view/returns/SelectTable.java
Labels: update

#212 197/ return & extend Page Update
  Library_System/src/view/extend/ExtendFrame.java
  Library_System/src/view/extend/ExtendTable.java
  Library_System/src/view/returns/ReturnFrame.java
  Library_System/src/view/returns/ReturnTable.java
Labels: update

#217 Update/rental table
  Library_System/src/view/defaultcomponent/BookListTable.java
  Library_System/src/view/rental/RentalTopPane.java
  Library_System/src/view/rental/RentalUnderPane.java
  Library_System/src/view/rental/SearchedTableTopPanel.java
  Library_System/src/view/rental/SearchedTableUnderPanel.java
  Library_System/src/view/rental/rentalEndPage/EndPanel.java
Labels: update

#216 main/214/뒤로가기 버튼 수정
  Library_System/src/view/main/MainButton.java
  Library_System/src/view/main/TopPanel.java
  Library_System/src/view/rental/RentalMainFrame.java
  Library_System/src/view/rental/SearchedTableTopPanel.java
  Library_System/src/view/rental/SelectBtnAction.java
  Library_System/src/view/rental/SelectBtnActionMain.java
  Library_System/src/view/rental/rentalEndPage/EndPageTimeLabel.java
  Library_System/src/view/rental/rentalEndPage/RentalEndFrame.java
  Library_System/src/view/rental/rentalEndPage/RentalEndHomeBtn.java
Labels: update

#215 update: returnTable 한글깨짐, ExtendTable 하이라이트 수정
  Library_System/src/view/extend/ExtendTable.java
  Library_System/src/view/returns/ReturnTable.java
Labels: update

#219 LoanDAO 수정
  Library_System/src/model/dao/LoanDao.java
Labels: update

#220 Test
  Library_System/src/main/Main.java
  Library_System/src/view/defaultcomponent/BookListPagingButton.java
  Library_System/src/view/defaultcomponent/BookListTable.java
  Library_System/src/view/defaultcomponent/NextPrevTablePagingButton.java
  Library_System/src/view/manager/TitlePanel.java
Labels: update

#222 update: Dao, Dto 정리
  Library_System/src/model/dao/BookClassificationDao.java
  Library_System/src/model/dao/OverdueCountDao.java
  Library_System/src/model/dao/OverdueDao.java
  Library_System/src/model/dto/BookClassification.java
  Library_System/src/model/dto/Overdue.java
  Library_System/src/model/dto/OverdueCount.java
Labels: update

#226 Test
  Library_System/src/view/advertising/AdImageButton.java
  Library_System/src/view/advertising/AdvertisingFrame.java
  Library_System/src/view/advertising/details/AdDetailsView.java
  Library_System/src/view/advertising/details/AdDetailsViewButton.java
  Library_System/src/view/rental/RentalMainFrame.java
  Library_System/src/view/rental/SelectBtnAction.java
  Library_System/src/view/rental/rentalEndPage/EndPageTimeLabel.java
  Library_System/src/view/rental/rentalEndPage/EndPanel.java
  Library_System/src/view/rental/rentalEndPage/EndpageLabel.java
  Library_System/src/view/rental/rentalEndPage/RentalEndFrame.java
  Library_System/src/view/rental/rentalEndPage/RentalEndHomeBtn.java
Labels: bug, duplicate, update

#227 Error/manager page
  Library_System/src/model/dao/AllBookInfoDao.java
  Library_System/src/view/manager/ManagerFrame.java
  Library_System/src/view/manager/TitlePanel.java
  Library_System/src/view/manager/dialog/ButtonPanel.java
  Library_System/src/view/manager/dialog/ManagerDialog.java
  Library_System/src/view/rental/SearchedTableTopPanel.java
  Library_System/src/view/rental/SearchedTableUnderPanel.java
Labels: bug, update

#232 Update/231/manager&rental page
  Library_System/src/model/dao/AllBookInfoDao.java
  Library_System/src/view/defaultcomponent/DefaultBookCategoryDropDown.java
  Library_System/src/view/manager/ManagerFrame.java
  Library_System/src/view/rental/RentalMain.java
Labels: update

#234 Test
  Library_System/src/db/DBConnector.java
  Library_System/src/view/advertising/AdActionButton.java
  Library_System/src/view/advertising/AdCenterPanel.java
  Library_System/src/view/advertising/AdTitleLabel.java
  Library_System/src/view/advertising/AdTopPanel.java
  Library_System/src/view/advertising/AdvertisingFrame.java
  Library_System/src/view/advertising/NewBookPanel.java
  Library_System/src/view/advertising/SuggestionBookPanel.java
  Library_System/src/view/rental/SelectBtnAction.java
  Library_System/src/view/rental/rentalEndPage/EndPageTimeLabel.java
Labels: bug, update

#224 update: 대여페이지 사용 예정
  Library_System/src/model/dao/OverdueCountDao.java
  Library_System/src/model/dto/OverdueCount.java
Labels: update

#236 Delete blank
  Library_System/src/view/login/LoginFrame.java
  Library_System/src/view/login/PwTextField.java
  Library_System/src/view/manager/ManagerFrame.java
  Library_System/src/view/rental/RentalMain.java
Labels: update

#237 update logic that delete loginField blank
  Library_System/src/view/login/LoginFrame.java
Labels: duplicate, update

#238 Error dao
  Library_System/image/COSMOS.jpg
  Library_System/src/model/dao/AllBookInfoDao.java
  Library_System/src/model/dao/LoanDao.java
  Library_System/src/model/dto/Loan.java
  Library_System/src/view/extend/ExtendTable.java
  Library_System/src/view/manager/TitlePanel.java
  Library_System/src/view/manager/dialog/ButtonPanel.java
  Library_System/src/view/returns/ReturnTable.java
Labels: bug, update
